apiVersion: v1
data:
  CELERY_BROKER_URL: redis://redis-server-service.default.svc.cluster.local:6379/0
  CELERY_RESULT_BACKEND: redis://redis-server-service.default.svc.cluster.local:6379/0
  SESSION_REDIS: redis-server-service.default.svc.cluster.local
kind: ConfigMap
metadata:
  name: bmx-billing-report
  namespace: default
