version: '3'
services:
  redis-server:
    image: redis-server:latest
    ports:
      - "6379:6379"
  web:
    image: bmxbillingreport:latest
    ports:
      - "5000:5000"
    depends_on:
      - redis-server

