apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-server-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: redis-server
    spec:
      containers:
      - name: redis-server
        image: registry.ng.bluemix.net/jonhall/redis-server:latest
        ports:
        - containerPort: 5000
